NAME_DISPLAY_MAP = {
    "vt_symbol": "原生代碼",
    "direction": "方向",
    "price": "價格",
    "volume": "數量",
    "time": "執行時間（秒）",
    "interval": "每輪間隔（秒）",
    "offset": "開平",
    "active": "演算法狀態",
    "traded": "成交數量",
    "order_volume": "單筆委託",
    "timer_count": "本輪讀秒",
    "total_count": "累計讀秒",
    "template_name": "演算法模板",
    "display_volume": "掛出數量",
    "stop_price": "觸發價格",
    "price_add": "委託超價",
    "step_price": "網格交易間距",
    "step_volume": "網格交易數量",
    "order_type": "型別",
    "active_vt_symbol": "主動腿",
    "passive_vt_symbol": "被動腿",
    "spread_up": "價差上限",
    "spread_down": "價差下限",
    "max_pos": "最大持倉"
}
